// data.js — Cyber·Math Academy
// Seluruh struktur belajar (cybersecurity + math), video per hari, dan playlist.

const CYBER_PHASES = [
  {
    id: "network",
    name: "Network+",
    days: [1, 7],
    icon: "🌐",
    desc: "Fondasi jaringan: OSI model, IP addressing, subnetting, routing, VLAN, wireless, troubleshooting.",
    playlist: {
      title: "Professor Messer — Network+ N10-009",
      url: "https://www.youtube.com/playlist?list=PLG49S3nxzAnl_tQe3kvnmeMid0mjF8Le8",
    },
    videos: [
      "How to Pass Your CompTIA N10-009 Network+ Exam",
      "Understanding the OSI Model",
      "Networking Devices",
      "Networking Functions",
      "Designing the Cloud",
      "Cloud Models",
      "Introduction to IP",
      "Common Ports",
      "Other Useful Protocols",
      "Network Communication",
      "Wireless Networking",
      "Ethernet Standards",
      "Optical Fiber",
      "Copper Cabling",
      "Network Transceivers",
      "Fiber Connectors",
      "Copper Connectors",
      "Network Topologies",
      "Network Architectures",
      "Binary Math",
      "IPv4 Addressing",
      "Classful Subnetting",
      "IPv4 Subnet Masks",
      "Calculating IPv4 Subnets and Hosts",
      "Magic Number Subnetting",
      "Seven Second Subnetting",
      "Software Defined Networking",
      "Virtual Extensible LAN",
      "Zero Trust",
      "Infrastructure as Code",
      "IPv6 Addressing",
      "Static Routing",
      "Dynamic Routing",
      "Routing Technologies",
      "Network Address Translation",
      "VLANs and Trunking",
      "Interface Configurations",
      "Spanning Tree Protocol",
      "Wireless Technologies",
      "Wireless Networking",
      "Network Types",
      "Wireless Encryption",
      "Installing Networks",
      "Power",
      "Environmental Factors",
      "Network Documentation",
      "Life Cycle Management",
      "Configuration Management",
      "SNMP",
      "Logs and Monitoring",
      "Network Solutions",
      "Disaster Recovery",
      "Network Redundancy",
      "DHCP",
      "Configuring DHCP",
      "IPv6 and SLAAC",
      "An Overview of DNS",
      "DNS Records",
      "Time Protocols",
      "VPNs",
      "Remote Access",
      "Security Concepts",
      "Authentication",
      "Security Technologies",
      "Regulatory Compliance",
      "Segmentation Enforcement",
      "Denial of Service",
      "VLAN Hopping",
      "MAC Flooding",
      "ARP and DNS Poisoning",
      "Rogue Services",
      "Social Engineering",
      "Malware",
      "Device Security",
      "Security Rules",
      "Network Troubleshooting Methodology",
      "Cable Issues",
      "Interface Issues",
      "Hardware Issues",
      "Switching Issues",
      "Routing and IP Issues",
      "Performance Issues",
      "Wireless Issues",
      "Software Tools",
      "Command Line Tools",
      "Hardware Tools",
      "Basic Network Device Commands",
    ],
  },
  {
    id: "security",
    name: "Security+",
    days: [8, 14],
    icon: "🛡️",
    desc: "Prinsip keamanan: threat, vulnerability, cryptography, identity, risk, dan arsitektur keamanan.",
    playlist: {
      title: "Professor Messer — Security+ SY0-701",
      url: "https://www.youtube.com/playlist?list=PLG49S3nxzAnl4QDVqK-hOnoqcSKEIDDuv",
    },
    videos: [
      "How to Pass Your SY0-701 Security+ Exam",
      "Security Goals",
      "Security Controls",
      "Security Roles and Responsibilities",
      "General Security Concepts",
      "Change Management",
      "Risk Management",
      "Threat Actors",
      "Common Threat Vectors",
      "Social Engineering",
      "Phishing",
      "Memory Injections",
      "Buffer Overflows",
      "Race Conditions",
      "Malicious Code",
      "Physical Attacks",
      "Adversarial AI",
      "Supply Chain Attacks",
      "Cloud Infrastructure",
      "Cloud Security",
      "Network Infrastructure",
      "Application Attacks",
      "Cryptographic Attacks",
      "Password Attacks",
      "Indicators of Compromise",
      "Segmentation",
      "Access Control",
      "Least Privilege",
      "Secure Protocols",
      "Firmware Security",
      "Endpoint Security",
      "Hardening",
      "Wireless Security",
      "Mobile Device Security",
      "Application Security",
      "Vulnerability Scanning",
      "Cryptography Fundamentals",
      "Symmetric Encryption",
      "Asymmetric Encryption",
      "Hashing",
      "Digital Signatures",
      "PKI and Certificates",
      "Key Management",
      "Authentication Methods",
      "Authorization Models",
      "Accounting and Auditing",
      "Identity Providers",
      "Federation",
      "Access Control Models",
      "Physical Security",
      "Network Security Appliances",
      "Secure Network Design",
      "Network Security Protocols",
      "Wireless Security Protocols",
      "Application Security Controls",
      "Secure Coding",
      "Virtualization Security",
      "Cloud Security Solutions",
      "Infrastructure as Code",
      "Incident Response",
      "Digital Forensics",
      "Disaster Recovery",
      "Business Continuity",
      "Risk Management Frameworks",
      "Security Policies",
      "Security Standards",
      "Security Procedures",
      "Governance",
      "Compliance",
      "Risk Assessment",
      "Third-Party Risk",
      "Data Protection",
      "Data Classification",
      "Data States",
      "Data Sovereignty",
      "Log Management",
      "SIEM",
      "SOAR",
      "Threat Intelligence",
      "Vulnerability Management",
      "Penetration Testing",
      "Security Automation",
      "PKI Management",
      "Certificate Management",
      "Cryptographic Concepts",
      "Digital Certificates",
      "Secure Communications",
      "Network Attacks",
      "Application Attacks",
      "Cryptographic Attacks",
      "Password Attacks",
      "Physical Attacks",
      "Social Engineering Attacks",
      "Web Attacks",
      "Cloud Attacks",
      "Mobile Attacks",
      "IoT Attacks",
      "AI Attacks",
      "Supply Chain Attacks",
      "Risk Management",
      "Business Impact Analysis",
      "Incident Response Planning",
      "Disaster Recovery Planning",
      "Business Continuity Planning",
      "Tabletop Exercises",
      "Security Awareness",
      "Security Training",
      "User Behavior Analytics",
      "Identity and Access Management",
      "Privileged Access Management",
      "Zero Trust Architecture",
      "Microsegmentation",
      "Secure Access Service Edge",
      "Software Defined Networking",
      "Cloud Access Security Broker",
      "Network Access Control",
      "Virtual Private Networks",
      "Secure Sockets Layer",
      "Transport Layer Security",
      "Internet Protocol Security",
      "Secure Shell",
      "Wireless Protected Access",
      "Authentication Protocols",
      "Remote Access",
      "End-to-End Encryption",
    ],
  },
  {
    id: "linux",
    name: "Linux",
    days: [15, 28],
    icon: "🐧",
    desc: "Sistem operasi Linux: command line, filesystem, permissions, shell scripting, dan administrasi dasar.",
    resources: [
      { name: "Linux Journey", url: "https://linuxjourney.com/", type: "tutorial" },
      { name: "Linux Unhatched (Cisco NetAcad)", url: "https://www.netacad.com/courses/linux-unhatched", type: "course" },
      { name: "LabEx — Linux Hands-on Labs", url: "https://labex.io/free-labs/linux", type: "labs" },
    ],
    tasks: [
      "Pelajari command line dasar (ls, cd, pwd, mkdir, rm, cp, mv)",
      "Pahami struktur filesystem Linux (/, /etc, /var, /home)",
      "Pelajari permissions & ownership (chmod, chown, umask)",
      "Pelajari proses & manajemen job (ps, top, kill, &)",
      "Pelajari redirection & pipes (>, >>, |)",
      "Pelajari text processing (grep, sed, awk, sort, uniq)",
      "Pelajari package management (apt/dnf)",
      "Pelajari networking dasar (ip, ss, ping, curl)",
      "Pelajari user & group management",
      "Pelajari cron jobs & scheduling",
      "Pelajari shell scripting dasar",
      "Selesaikan Linux Unhatched (Cisco NetAcad)",
      "Selesaikan lab Linux di LabEx",
      "Praktik: buat script backup otomatis sederhana",
    ],
  },
  {
    id: "python",
    name: "Python",
    days: [29, 42],
    icon: "🐍",
    desc: "Pemrograman Python untuk keamanan: sintaks, struktur data, scripting, dan otomasi.",
    resources: [
      { name: "freeCodeCamp — Learn Python (Full Course)", url: "https://www.youtube.com/watch?v=rfscVS0vtbw", type: "video" },
      { name: "Codecademy — Learn Python", url: "https://codecademy.com/learn/learn-python", type: "course" },
      { name: "SoloLearn — Python Tutorial", url: "https://sololearn.com/Course/Python/", type: "tutorial" },
      { name: "Real Python", url: "https://realpython.com/", type: "reference" },
      { name: "HackerRank — Python", url: "https://www.hackerrank.com/domains/python", type: "practice" },
      { name: "LabEx — Python by Labs", url: "https://labex.io/free-labs/python", type: "labs" },
      { name: "TheCyberMentor — Python for Cybersecurity", url: "https://www.youtube.com/watch?v=egg-GoT5iVk", type: "video" },
    ],
    tasks: [
      "Pelajari variabel, tipe data, dan operator",
      "Pelajari kontrol alur (if/else, loop)",
      "Pelajari fungsi & scope",
      "Pelajari list, tuple, dict, set",
      "Pelajari string manipulation",
      "Pelajari file I/O (baca/tulis file)",
      "Pelajari exception handling (try/except)",
      "Pelajari modul & packages",
      "Pelajari regular expression (re)",
      "Pelajari networking dengan socket",
      "Pelajari HTTP requests (requests library)",
      "Selesaikan Python track Codecademy (free tier)",
      "Kerjakan soal Python di HackerRank",
      "Praktik: buat port scanner sederhana (lab legal)",
    ],
  },
  {
    id: "traffic",
    name: "Traffic Analysis",
    days: [43, 56],
    icon: "📡",
    desc: "Analisis lalu lintas jaringan: Wireshark, tcpdump, Suricata IDS/IPS, dan packet inspection.",
    resources: [
      { name: "Wireshark University", url: "https://www.wireshark.org/#educationalContent", type: "course" },
      { name: "Wireshark Tutorial (Guru99)", url: "https://guru99.com/wireshark-tutorial.html", type: "tutorial" },
      { name: "TCPdump Tutorial (Daniel Miessler)", url: "https://danielmiessler.com/study/tcpdump/", type: "tutorial" },
      { name: "Suricata Quickstart Guide", url: "https://docs.suricata.io/en/latest/quickstart.html", type: "docs" },
      { name: "Wireshark Tutorial for Beginners (YouTube)", url: "https://www.youtube.com/watch?v=NjvR4LmwcMU&list=PLBf0hzazHTGPgyxeEj_9LBHiqjtNEjsgt", type: "video" },
      { name: "Suricata Network IDS/IPS (YouTube)", url: "https://www.youtube.com/watch?v=S0-vsjhPDN0", type: "video" },
    ],
    tasks: [
      "Pelajari cara menangkap packet dengan Wireshark",
      "Pahami display filter & capture filter",
      "Analisis handshake TCP (SYN, SYN-ACK, ACK)",
      "Analisis HTTP/DNS traffic",
      "Pelajari tcpdump command line",
      "Pelajari dasar Suricata rules",
      "Deteksi pola mencurigakan di traffic",
      "Praktik: analisis file .pcap sample",
    ],
  },
  {
    id: "git",
    name: "Git",
    days: [57, 63],
    icon: "🔀",
    desc: "Version control dengan Git: commit, branch, merge, rebase, dan workflow kolaborasi.",
    resources: [
      { name: "Codecademy — Git for Beginners", url: "https://codecademy.com/learn/learn-git", type: "course" },
      { name: "Git Immersion", url: "http://gitimmersion.com", type: "tutorial" },
      { name: "Try Git", url: "https://try.github.io", type: "interactive" },
      { name: "Learn Git Branching", url: "https://learngitbranching.js.org/", type: "interactive" },
    ],
    tasks: [
      "Pelajari git init, add, commit, status, log",
      "Pelajari branch, checkout, merge",
      "Pelajari remote (push, pull, fetch)",
      "Pelajari rebase & conflict resolution",
      "Pelajari .gitignore & best practices",
      "Selesaikan Learn Git Branching",
      "Praktik: kelola repo project sendiri di GitHub",
    ],
  },
  {
    id: "elk",
    name: "ELK Stack",
    days: [64, 70],
    icon: "📊",
    desc: "SIEM & log analysis dengan Elasticsearch, Logstash, Kibana.",
    resources: [
      { name: "Complete Guide to ELK Stack (Logz.io)", url: "https://logz.io/learn/complete-guide-elk-stack/", type: "tutorial" },
      { name: "Elastic Stack Getting Started", url: "https://www.elastic.co/docs/get-started", type: "docs" },
    ],
    tasks: [
      "Pahami konsep SIEM & log management",
      "Pelajari Elasticsearch (index, query)",
      "Pelajari Logstash (ingest & pipeline)",
      "Pelajari Kibana (visualisasi & dashboard)",
      "Praktik: ingest sample logs & buat dashboard",
    ],
  },
  {
    id: "cloud",
    name: "Cloud Platforms",
    days: [71, 77],
    icon: "☁️",
    desc: "Keamanan cloud: pilih salah satu antara GCP, AWS, atau Azure.",
    resources: [
      { name: "AWS Getting Started", url: "https://aws.amazon.com/getting-started/", type: "tutorial" },
      { name: "AWS Tutorials", url: "https://aws.amazon.com/tutorials/", type: "tutorial" },
      { name: "AWS Cloud Quest", url: "https://aws.amazon.com/training/digital/aws-cloud-quest/", type: "interactive" },
      { name: "Azure Fundamentals (Microsoft Learn)", url: "https://learn.microsoft.com/en-us/training/azure/", type: "course" },
      { name: "GCP Getting Started", url: "https://cloud.google.com/getting-started/", type: "tutorial" },
      { name: "Google Cloud Skills Boost", url: "https://www.cloudskillsboost.google", type: "labs" },
    ],
    tasks: [
      "Pilih satu cloud provider (AWS/Azure/GCP)",
      "Pelajari konsep IAM & least privilege",
      "Pelajari virtual network / VPC",
      "Pelajari storage & compute services",
      "Pelajari cloud security best practices",
      "Praktik: deploy resource di free tier",
    ],
  },
  {
    id: "review",
    name: "Review & Practice",
    days: [78, 84],
    icon: "🔁",
    desc: "Ulangi materi lemah, kerjakan lab TryHackMe, dan bangun home lab.",
    resources: [
      { name: "TryHackMe", url: "https://tryhackme.com", type: "labs" },
      { name: "VirtualBox", url: "https://www.virtualbox.org/", type: "tool" },
      { name: "VMware Workstation Player", url: "https://www.vmware.com/products/workstation-player.html", type: "tool" },
    ],
    tasks: [
      "Review materi Day 1-77 yang masih lemah",
      "Selesaikan challenge di TryHackMe",
      "Setup home lab (VirtualBox/VMware)",
      "Bangun project kecil gabungan networking+Linux+Python+security",
    ],
  },
  {
    id: "hacking",
    name: "Hacking",
    days: [85, 90],
    icon: "🎯",
    desc: "Penetration testing & ethical hacking: Hack The Box, Vulnhub, dan video TheCyberMentor.",
    resources: [
      { name: "Hack The Box", url: "https://hackthebox.com", type: "labs" },
      { name: "Vulnhub", url: "https://vulnhub.com", type: "labs" },
      { name: "Cyber Talents", url: "https://cybertalents.com", type: "labs" },
      { name: "TheCyberMentor — Ethical Hacking Part 1", url: "https://www.youtube.com/watch?v=3FNYvj2U0HM", type: "video" },
      { name: "TheCyberMentor — Ethical Hacking Part 2", url: "https://www.youtube.com/watch?v=sH4JCwjybGs", type: "video" },
    ],
    tasks: [
      "Pelajari methodology penetration testing",
      "Pelajari reconnaissance & enumeration",
      "Kerjakan mesin vulnerable di HTB/Vulnhub",
      "Tonton Ethical Hacking Part 1 & 2",
      "Praktik di lab legal saja (HTB/Vulnhub/TryHackMe)",
    ],
  },
  {
    id: "career",
    name: "Career",
    days: [91, 95],
    icon: "💼",
    desc: "Landing the job: resume satu halaman dan cara melamar.",
    resources: [
      { name: "Killer Cyber Resume (BowTiedCyber)", url: "https://bowtiedcyber.substack.com/p/killer-cyber-resume-part-ii", type: "guide" },
      { name: "Indeed", url: "https://indeed.com", type: "jobs" },
      { name: "LinkedIn", url: "https://linkedin.com", type: "jobs" },
      { name: "CyberSeek Career Pathways", url: "https://www.cyberseek.org/pathway.html", type: "reference" },
    ],
    tasks: [
      "Buat resume satu halaman (simpan juga sebagai cv.md)",
      "Daftarkan pengalaman lab/CTF/project ke resume",
      "Riset career pathway di CyberSeek",
      "Siapkan profil LinkedIn",
    ],
  },
];

const MATH_PLAYLISTS = [
  {
    id: "all-math",
    name: "Mathematics (All Of It)",
    icon: "🧠",
    color: "slate",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9FoGQeUMFZ4SWZsr30jlUYK",
    desc: "Playlist induk: seluruh matematika dari aritmetika dasar hingga kalkulus multivariabel & persamaan diferensial (193 video).",
    videos: [
      "Introduction to Mathematics",
      "Addition and Subtraction of Small Numbers",
      "Multiplication and Division of Small Numbers",
      "Understanding Fractions, Improper Fractions, and Mixed Numbers",
      "Large Whole Numbers: Place Values and Estimating",
      "Decimals: Notation and Operations",
      "Working With Percentages",
      "Converting Between Fractions, Decimals, and Percentages",
      "Addition and Subtraction of Large Numbers",
      "The Distributive Property for Arithmetic",
      "Multiplication of Large Numbers",
      "Division of Large Numbers: Long Division",
      "Negative Numbers",
      "Understanding Exponents and Their Operations",
      "Order of Arithmetic Operations: PEMDAS",
      "Divisibility, Prime Numbers, and Prime Factorization",
      "Least Common Multiple (LCM)",
      "Greatest Common Factor (GCF)",
      "Addition and Subtraction of Fractions",
      "Multiplication and Division of Fractions",
      "Analyzing Sets of Data: Range, Mean, Median, and Mode",
      "Introduction to Algebra: Using Variables",
      "Basic Number Properties for Algebra",
      "Algebraic Equations and Their Solutions",
      "Algebraic Equations With Variables on Both Sides",
      "Algebraic Word Problems",
      "Solving Algebraic Inequalities",
      "Square Roots, Cube Roots, and Other Roots",
      "Simplifying Expressions With Roots and Exponents",
      "Solving Algebraic Equations With Roots and Exponents",
      "Introduction to Polynomials",
      "Adding and Subtracting Polynomials",
      "Multiplying Binomials by the FOIL Method",
      "Solving Quadratics by Factoring",
      "Solving Quadratics by Completing the Square",
      "Solving Quadratics by Using the Quadratic Formula",
      "Solving Higher-Degree Polynomials by Synthetic Division and the Rational Roots Test",
      "Manipulating Rational Expressions: Simplification and Operations",
      "Graphing in Algebra: Ordered Pairs and the Coordinate Plane",
      "Graphing Lines in Algebra: Understanding Slopes and Y-Intercepts",
      "Graphing Lines in Slope-Intercept Form (y = mx + b)",
      "Graphing Lines in Standard Form (ax + by = c)",
      "Graphing Parallel and Perpendicular Lines",
      "Solving Systems of Two Equations and Two Unknowns: Graphing, Substitution, and Elimination",
      "Absolute Values: Defining, Calculating, and Graphing",
      "What are the Types of Numbers? Real vs. Imaginary, Rational vs. Irrational",
      "Introduction to Geometry: Ancient Greece and the Pythagoreans",
      "Basic Euclidean Geometry: Points, Lines, and Planes",
      "Types of Angles and Angle Relationships",
      "Types of Triangles in Euclidean Geometry",
      "Proving Triangle Congruence and Similarity",
      "Special Lines in Triangles: Bisectors, Medians, and Altitudes",
      "The Triangle Midsegment Theorem",
      "The Pythagorean Theorem",
      "Types of Quadrilaterals and Other Polygons",
      "Calculating the Perimeter of Polygons",
      "Circles: Radius, Diameter, Chords, Circumference, and Sectors",
      "Calculating the Area of Shapes",
      "Proving the Pythagorean Theorem",
      "Three-Dimensional Shapes Part 1: Types, Calculating Surface Area",
      "Three-Dimensional Shapes Part 2: Calculating Volume",
      "Back to Algebra: What are Functions?",
      "Manipulating Functions Algebraically and Evaluating Composite Functions",
      "Graphing Algebraic Functions: Domain and Range, Maxima and Minima",
      "Transforming Algebraic Functions: Shifting, Stretching, and Reflecting",
      "Continuous, Discontinuous, and Piecewise Functions",
      "Inverse Functions",
      "The Distance Formula: Finding the Distance Between Two Points",
      "Graphing Conic Sections Part 1: Circles",
      "Graphing Conic Sections Part 2: Ellipses",
      "Graphing Conic Sections Part 3: Parabolas in Standard Form",
      "Graphing Conic Sections Part 4: Hyperbolas",
      "Graphing Higher-Degree Polynomials: The Leading Coefficient Test and Finding Zeros",
      "Graphing Rational Functions and Their Asymptotes",
      "Solving and Graphing Polynomial and Rational Inequalities",
      "Evaluating and Graphing Exponential Functions",
      "Logarithms Part 1: Evaluation of Logs and Graphing Logarithmic Functions",
      "Logarithms Part 2: Base Ten Logs, Natural Logs, and the Change-Of-Base Property",
      "Logarithms Part 3: Properties of Logs, Expanding Logarithmic Expressions",
      "Solving Exponential and Logarithmic Equations",
      "Complex Numbers: Operations, Complex Conjugates, and the Linear Factorization Theorem",
      "Set Theory: Types of Sets, Unions and Intersections",
      "Sequences, Factorials, and Summation Notation",
      "Theoretical Probability, Permutations and Combinations",
      "Introduction to Trigonometry: Angles and Radians",
      "Trigonometric Functions: Sine, Cosine, Tangent, Cosecant, Secant, and Cotangent",
      "The Easiest Way to Memorize the Trigonometric Unit Circle",
      "Basic Trigonometric Identities: Pythagorean Identities and Cofunction Identities",
      "Graphing Trigonometric Functions",
      "Inverse Trigonometric Functions",
      "Verifying Trigonometric Identities",
      "Formulas for Trigonometric Functions: Sum/Difference, Double/Half-Angle, Prod-to-Sum/Sum-to-Prod",
      "Solving Trigonometric Equations",
      "The Law of Sines",
      "The Law of Cosines",
      "Polar Coordinates and Graphing Polar Equations",
      "Parametric Equations",
      "Introduction to Calculus: The Greeks, Newton, and Leibniz",
      "Understanding Differentiation Part 1: The Slope of a Tangent Line",
      "Understanding Differentiation Part 2: Rates of Change",
      "Limits and Limit Laws in Calculus",
      "What is a Derivative? Deriving the Power Rule",
      "Derivatives of Polynomial Functions: Power Rule, Product Rule, and Quotient Rule",
      "Derivatives of Trigonometric Functions",
      "Derivatives of Composite Functions: The Chain Rule",
      "Derivatives of Logarithmic and Exponential Functions",
      "Implicit Differentiation",
      "Higher Derivatives and Their Applications",
      "Related Rates in Calculus",
      "Finding Local Maxima and Minima by Differentiation",
      "Graphing Functions and Their Derivatives",
      "Optimization Problems in Calculus",
      "Understanding Limits and L'Hospital's Rule",
      "What is Integration? Finding the Area Under a Curve",
      "The Fundamental Theorem of Calculus: Redefining Integration",
      "Properties of Integrals and Evaluating Definite Integrals",
      "Evaluating Indefinite Integrals",
      "Evaluating Integrals With Trigonometric Functions",
      "Integration Using The Substitution Rule",
      "Integration By Parts",
      "Integration By Trigonometric Substitution",
      "Advanced Strategy for Integration in Calculus",
      "Evaluating Improper Integrals",
      "Finding the Area Between Two Curves by Integration",
      "Calculating the Volume of a Solid of Revolution by Integration",
      "Calculating Volume by Cylindrical Shells",
      "The Mean Value Theorem For Integrals: Average Value of a Function",
      "Convergence and Divergence: The Return of Sequences and Series",
      "Estimating Sums Using the Integral Test and Comparison Test",
      "Alternating Series, Types of Convergence, and the Ratio Test",
      "Power Series",
      "Taylor and Maclaurin Series",
      "Hyperbolic Functions: Definitions, Identities, Derivatives, and Inverses",
      "Three-Dimensional Coordinates and the Right-Hand Rule",
      "Introduction to Vectors and Their Operations",
      "The Vector Dot Product",
      "Introduction to Linear Algebra: Systems of Linear Equations",
      "Understanding Matrices and Matrix Notation",
      "Manipulating Matrices: Elementary Row Operations and Gauss-Jordan Elimination",
      "Types of Matrices and Matrix Addition",
      "Matrix Multiplication and Associated Properties",
      "Evaluating the Determinant of a Matrix",
      "The Vector Cross Product",
      "Inverse Matrices and Their Properties",
      "Solving Systems Using Cramer's Rule",
      "Understanding Vector Spaces",
      "Subspaces and Span",
      "Linear Independence",
      "Basis and Dimension",
      "Change of Basis",
      "Linear Transformations on Vector Spaces",
      "Image and Kernel",
      "Orthogonality and Orthonormality",
      "The Gram-Schmidt Process",
      "Finding Eigenvalues and Eigenvectors",
      "Diagonalization",
      "Complex, Hermitian, and Unitary Matrices",
      "Further Matrix Decompositions: LU, Cholesky, QR, and SVD",
      "Double and Triple Integrals",
      "Partial Derivatives and the Gradient of a Function",
      "Vector Fields, Divergence, and Curl",
      "Evaluating Line Integrals",
      "Green's Theorem",
      "Evaluating Surface Integrals",
      "Stokes's Theorem",
      "The Divergence Theorem",
      "Introduction to Differential Equations",
      "Classification of Differential Equations",
      "Separable First-Order Differential Equations",
      "Linear First-Order Differential Equations",
      "Exact First-Order Differential Equations",
      "Homogeneous Differential Equations and Bernoulli Differential Equations",
      "Linear Second-Order Differential Equations Part 1: Homogeneous Case",
      "Linear Second-Order Differential Equations Part 2: Non-Homogeneous Differential Equations",
      "Special Second-Order Differential Equations: Cauchy-Euler, Nonlinear, and More",
      "Numerical Methods for Solving Differential Equations",
      "Power Series Solutions Part 1: Leibniz Method",
      "Power Series Solutions Part 2: Frobenius Method",
      "Systems of Differential Equations Part 1: Modeling and Elimination",
      "Systems of Differential Equations Part 2: Matrices and Stability",
      "Laplace Transforms Part 1: Solving Differential Equations",
      "Laplace Transforms Part 2: Convolutions and LTI Systems",
      "Difference Equations and Z-Transforms",
      "Introduction to Partial Differential Equations: Classification and Differential Operators",
      "Quasi-Linear First-Order Partial Differential Equations: Lagrange’s Method",
      "Laplace’s Equation: Separation of Variables",
      "Fourier Series and Transforms Part 1: Concepts in Frequency Analysis",
      "Fourier Series and Transforms Part 2: Power Spectra and K-Space",
      "The Wave Equation Part 1: Vibrations in 1D",
      "The Wave Equation Part 2: Multidimensional Waves and Dispersion",
      "The Diffusion Equation Part 1: Separation of Variables",
      "The Diffusion Equation Part 2: Dimensional Analysis and Self-Similarity",
      "The Diffusion Equation Part 3: Green’s Functions",
    ],
  },
  {
    id: "algebra",
    name: "Algebra 1 & 2",
    icon: "🔢",
    color: "blue",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9FoUSDODs14ck3OzSje4WZb",
    desc: "Variabel, persamaan, polinomial, fungsi, logaritma, dan bilangan kompleks.",
    videos: [
      "Introduction to Algebra: Using Variables",
      "Basic Number Properties for Algebra",
      "Algebraic Equations and Their Solutions",
      "Algebraic Equations With Variables on Both Sides",
      "Algebraic Word Problems",
      "Solving Algebraic Inequalities",
      "Square Roots, Cube Roots, and Other Roots",
      "Simplifying Expressions With Roots and Exponents",
      "Solving Algebraic Equations With Roots and Exponents",
      "Introduction to Polynomials",
      "Adding and Subtracting Polynomials",
      "Multiplying Binomials by the FOIL Method",
      "Solving Quadratics by Factoring",
      "Solving Quadratics by Completing the Square",
      "Solving Quadratics by Using the Quadratic Formula",
      "Solving Higher-Degree Polynomials by Synthetic Division and the Rational Roots Test",
      "Manipulating Rational Expressions: Simplification and Operations",
      "Graphing in Algebra: Ordered Pairs and the Coordinate Plane",
      "Graphing Lines in Algebra: Understanding Slopes and Y-Intercepts",
      "Graphing Lines in Slope-Intercept Form (y = mx + b)",
      "Graphing Lines in Standard Form (ax + by = c)",
      "Graphing Parallel and Perpendicular Lines",
      "Solving Systems of Two Equations and Two Unknowns",
      "Absolute Values: Defining, Calculating, and Graphing",
      "What are the Types of Numbers? Real vs. Imaginary, Rational vs. Irrational",
      "Back to Algebra: What are Functions?",
      "Manipulating Functions Algebraically and Evaluating Composite Functions",
      "Graphing Algebraic Functions: Domain and Range, Maxima and Minima",
      "Transforming Algebraic Functions: Shifting, Stretching, and Reflecting",
      "Continuous, Discontinuous, and Piecewise Functions",
      "Inverse Functions",
      "The Distance Formula: Finding the Distance Between Two Points",
      "Graphing Conic Sections Part 1: Circles",
      "Graphing Conic Sections Part 2: Ellipses",
      "Graphing Conic Sections Part 3: Parabolas in Standard Form",
      "Graphing Conic Sections Part 4: Hyperbolas",
      "Graphing Higher-Degree Polynomials: The Leading Coefficient Test and Finding Zeros",
      "Graphing Rational Functions and Their Asymptotes",
      "Solving and Graphing Polynomial and Rational Inequalities",
      "Evaluating and Graphing Exponential Functions",
      "Logarithms Part 1: Evaluation of Logs and Graphing Logarithmic Functions",
      "Logarithms Part 2: Base Ten Logs, Natural Logs, and the Change-Of-Base Property",
      "Logarithms Part 3: Properties of Logs, Expanding Logarithmic Expressions",
      "Solving Exponential and Logarithmic Equations",
      "Complex Numbers: Operations, Complex Conjugates, and the Linear Factorization Theorem",
      "Set Theory: Types of Sets, Unions and Intersections",
      "Sequences, Factorials, and Summation Notation",
      "Theoretical Probability, Permutations and Combinations",
    ],
  },
  {
    id: "geometry",
    name: "Geometry",
    icon: "📐",
    color: "green",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9GXX6XP_-m7GDS4N1iSdQ2g",
    desc: "Geometri Euclidean: sudut, segitiga, lingkaran, luas, dan bangun ruang.",
    videos: [
      "Introduction to Geometry: Ancient Greece and the Pythagoreans",
      "Basic Euclidean Geometry: Points, Lines, and Planes",
      "Types of Angles and Angle Relationships",
      "Types of Triangles in Euclidean Geometry",
      "Proving Triangle Congruence and Similarity",
      "Special Lines in Triangles: Bisectors, Medians, and Altitudes",
      "The Triangle Midsegment Theorem",
      "The Pythagorean Theorem",
      "Types of Quadrilaterals and Other Polygons",
      "Calculating the Perimeter of Polygons",
      "Circles: Radius, Diameter, Chords, Circumference, and Sectors",
      "Calculating the Area of Shapes",
      "Proving the Pythagorean Theorem",
      "Three-Dimensional Shapes Part 1: Types, Calculating Surface Area",
      "Three-Dimensional Shapes Part 2: Calculating Volume",
    ],
  },
  {
    id: "trigonometry",
    name: "Trigonometry",
    icon: "📏",
    color: "amber",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9GzztfmHCkH_5e6TLE9CfpK",
    desc: "Fungsi trigonometri, identitas, unit circle, dan aplikasi.",
    videos: [
      "Introduction to Trigonometry: Angles and Radians",
      "Trigonometric Functions: Sine, Cosine, Tangent, Cosecant, Secant, and Cotangent",
      "The Easiest Way to Memorize the Trigonometric Unit Circle",
      "Basic Trigonometric Identities: Pythagorean Identities and Cofunction Identities",
      "Graphing Trigonometric Functions",
      "Inverse Trigonometric Functions",
      "Verifying Trigonometric Identities",
      "Formulas for Trigonometric Functions: Sum/Difference, Double/Half-Angle",
      "Solving Trigonometric Equations",
      "The Law of Sines",
      "The Law of Cosines",
    ],
  },
  {
    id: "calculus",
    name: "Calculus",
    icon: "∫",
    color: "violet",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9ELZEe9s2NXTKr41Yedbw7M",
    desc: "Limit, derivative, integral, dan aplikasi kalkulus.",
    videos: [
      "Introduction to Calculus: The Greeks, Newton, and Leibniz",
      "Understanding Differentiation Part 1: The Slope of a Tangent Line",
      "Understanding Differentiation Part 2: Rates of Change",
      "Limits and Limit Laws in Calculus",
      "What is a Derivative? Deriving the Power Rule",
      "Derivatives of Polynomial Functions: Power Rule, Product Rule, and Quotient Rule",
      "Derivatives of Trigonometric Functions",
      "Derivatives of Composite Functions: The Chain Rule",
      "Derivatives of Logarithmic and Exponential Functions",
      "Implicit Differentiation",
      "Higher Derivatives and Their Applications",
      "Related Rates in Calculus",
      "Finding Local Maxima and Minima by Differentiation",
      "Graphing Functions and Their Derivatives",
      "Optimization Problems in Calculus",
      "Understanding Limits and L'Hospital's Rule",
      "What is Integration? Finding the Area Under a Curve",
      "The Fundamental Theorem of Calculus: Redefining Integration",
      "Properties of Integrals and Evaluating Definite Integrals",
      "Evaluating Indefinite Integrals",
      "Evaluating Integrals With Trigonometric Functions",
      "Integration Using The Substitution Rule",
      "Integration By Parts",
      "Integration By Trigonometric Substitution",
      "Advanced Strategy for Integration in Calculus",
      "Evaluating Improper Integrals",
      "Finding the Area Between Two Curves by Integration",
      "Calculating the Volume of a Solid of Revolution by Integration",
      "Calculating Volume by Cylindrical Shells",
      "The Mean Value Theorem For Integrals: Average Value of a Function",
      "Convergence and Divergence: The Return of Sequences and Series",
      "Estimating Sums Using the Integral Test and Comparison Test",
      "Alternating Series, Types of Convergence, and the Ratio Test",
      "Power Series",
      "Taylor and Maclaurin Series",
    ],
  },
  {
    id: "linear-algebra",
    name: "Linear Algebra",
    icon: "🧮",
    color: "cyan",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9En46TNCXL2n6SiqRc_iMB8",
    desc: "Matriks, vektor, transformasi linear, eigenvalues, dan dekomposisi.",
    videos: [
      "Introduction to Linear Algebra: Systems of Linear Equations",
      "Understanding Matrices and Matrix Notation",
      "Manipulating Matrices: Elementary Row Operations and Gauss-Jordan Elimination",
      "Types of Matrices and Matrix Addition",
      "Matrix Multiplication and Associated Properties",
      "Evaluating the Determinant of a Matrix",
      "The Vector Cross Product",
      "Inverse Matrices and Their Properties",
      "Solving Systems Using Cramer's Rule",
      "Understanding Vector Spaces",
      "Subspaces and Span",
      "Linear Independence",
      "Basis and Dimension",
      "Change of Basis",
      "Linear Transformations on Vector Spaces",
      "Image and Kernel",
      "Orthogonality and Orthonormality",
      "The Gram-Schmidt Process",
      "Finding Eigenvalues and Eigenvectors",
      "Diagonalization",
      "Complex, Hermitian, and Unitary Matrices",
      "Further Matrix Decompositions: LU, Cholesky, QR, and SVD",
    ],
  },
  {
    id: "differential-equations",
    name: "Differential Equations",
    icon: "∇",
    color: "rose",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9FwwFOmp8sGTHZRiTWPYSs1",
    desc: "Persamaan diferensial biasa & parsial, Laplace, Fourier, dan aplikasi fisika.",
    videos: [
      "Introduction to Differential Equations",
      "Classification of Differential Equations",
      "Separable First-Order Differential Equations",
      "Linear First-Order Differential Equations",
      "Exact First-Order Differential Equations",
      "Homogeneous Differential Equations and Bernoulli Differential Equations",
      "Linear Second-Order Differential Equations Part 1: Homogeneous Case",
      "Linear Second-Order Differential Equations Part 2: Non-Homogeneous",
      "Special Second-Order Differential Equations: Cauchy-Euler, Nonlinear, and More",
      "Numerical Methods for Solving Differential Equations",
      "Power Series Solutions Part 1: Leibniz Method",
      "Power Series Solutions Part 2: Frobenius Method",
      "Systems of Differential Equations Part 1: Modeling and Elimination",
      "Systems of Differential Equations Part 2: Matrices and Stability",
      "Laplace Transforms Part 1: Solving Differential Equations",
      "Laplace Transforms Part 2: Convolutions and LTI Systems",
      "Difference Equations and Z-Transforms",
      "Introduction to Partial Differential Equations",
      "Quasi-Linear First-Order Partial Differential Equations: Lagrange's Method",
      "Laplace's Equation: Separation of Variables",
      "Fourier Series and Transforms Part 1: Concepts in Frequency Analysis",
      "Fourier Series and Transforms Part 2: Power Spectra and K-Space",
      "The Wave Equation Part 1: Vibrations in 1D",
      "The Wave Equation Part 2: Multidimensional Waves and Dispersion",
      "The Diffusion Equation Part 1: Separation of Variables",
      "The Diffusion Equation Part 2: Dimensional Analysis and Self-Similarity",
      "The Diffusion Equation Part 3: Green's Functions",
    ],
  },
  {
    id: "advanced-math",
    name: "Advanced Math",
    icon: "🌌",
    color: "slate",
    url: "https://www.youtube.com/playlist?list=PLybg94GvOJ9GkwyYc3jolcsDgjl2Niarg",
    desc: "Kalkulus multivariabel: integral lipat, gradien, dan teorema vektor.",
    videos: [
      "Double and Triple Integrals",
      "Partial Derivatives and the Gradient of a Function",
      "Vector Fields, Divergence, and Curl",
      "Evaluating Line Integrals",
      "Green's Theorem",
      "Evaluating Surface Integrals",
      "Stokes's Theorem",
      "The Divergence Theorem",
    ],
  },
];
